version: "3.9"

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    ports:
      - "8000:8000"
    environment:
      # Example environment variables
      APP_ENV: "production"
      DEBUG: "false"
    volumes:
      - ./app:/app  # Bind mount for local development (optional)
    command: >
      uvicorn main:app
      --host 0.0.0.0
      --port 8000
